#certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
spec:
  secretName: trustorbs-tls
  privateKey:
    rotationPolicy: Always
  commonName: "${commonName}"
  dnsNames:
    - "${dnsNames}"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer