name: Deploy Azure Infrastructure and Helm Charts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure resources
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file infra/resource/trustorbs-resource-template.json \
          --parameters infra/resource/parameters.json \
          --parameters \
            servicePrincipalClientId=${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }} \
            servicePrincipalClientSecret=${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }} \
            objectId=${{ secrets.OBJECT_ID }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

    - name: Create Kubernetes namespace
      run: |
        kubectl create namespace test-trustorbs || echo "Namespace already exists"

    - name: Add Helm repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add codecentric https://codecentric.github.io/helm-charts

    - name: Update Helm repos
      run: |
        helm repo update

    - name: Install or Upgrade PostgreSQL using Helm
      run: |
        helm upgrade --install keycloak-db bitnami/postgresql \
          --namespace test-trustorbs \
          --values ./keycloak/keycloak-db-values.yaml

    - name: Install or Upgrade Keycloak using Helm with LoadBalancer
      run: |
        helm upgrade --install keycloak codecentric/keycloakx \
          --namespace test-trustorbs \
          --values ./keycloak/keycloak-server-values.yaml
